import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import MyNavbar from "@/components/MyNavbar";
import {Grid, Button, Row, Col, Container, useModal, Link} from "@nextui-org/react";
import MyTable from "@/components/MyTable";
import {Box} from "@/components/Box";
import MyChart from "@/components/MyChart";
import {useState,useEffect, SetStateAction} from "react";
import ModalListOfCampaign from "@/components/ModalListOfCampaign";



export default function CampaignDashboard() {
    const [csvData, setCsvData] = useState<any[]>([]);
    const [campaignId,setCampaignId] = useState(0)
    const [nameOfCampaign,setNameOfCampaign] = useState('')
    const [selectedItems, setSelectedItems] = useState([]);

    function handleSelectedItems(items: any) {
        setSelectedItems(items);
    }

    // @ts-ignore
    const { setVisible, bindings } = useModal();
    function back(){
        window.location.href = '/';
    }
    function generateCSV(){
        console.log(csvData);
        setCsvData([])
    }
    function showListOfCampaigns(){
        setVisible(true)
    }
    function sendWarning(){
        let selectedItemsArray:any=[];
        let csvData:any=[];
        // @ts-ignore
        if(selectedItems!='all')
            (selectedItems as any).forEach((value:any, key:any) => {
                selectedItemsArray.push(parseInt(key));
            });
        fetch(('http://localhost:3000/api/campaignDetails/'+campaignId))
        .then(response => response.json())
        .then(data => {
            for(let i=0;i<data.length;i++){
                // @ts-ignore
                if(selectedItemsArray.includes(data[i].id)||selectedItems=='all'){
                    csvData.push(data[i]);
                }
            }
            fetch(('http://localhost:3000/api/sendWarning/'), {
                method: 'POST',
                headers : { 'Content-Type': 'application/json' },
                body: JSON.stringify(csvData)
            })
        }).catch((error) => {
            console.error('Error:', error);
        });
    }
    return (
        <>
            <Head>
                <title>Campaign Dashboard</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>

                <MyNavbar title={nameOfCampaign}  />
                {/*<Box style={{width:'100%'}}>*/}
                    <ModalListOfCampaign bindings={bindings}  setVisible={setVisible} setCampaignId={setCampaignId} setNameofCampaign={setNameOfCampaign}/>
                    <Grid.Container gap={1} justify="center" css={{width:'100%'}}>
                        <Grid xs={12} md={6} lg={4} >
                            <Box  style={{background:'#3B4256',width:'100%',height:'100%',textAlign:'center'}}>
                                <h3>Lista Email</h3>
                            </Box>
                        </Grid>
                        <Grid xs={0} md={6} lg={8} >
                            <Box  style={{background:'#3B4256',width:'100%',height:'100%',textAlign:'center'}}>
                                <h3>Wykres</h3>
                            </Box>

                        </Grid>
                        <Grid xs={12} md={6} lg={4} css={{height:'75vh'}}>
                            <MyTable campaignId={campaignId} generateCSV={csvData} onSelectItems={handleSelectedItems}/>

                        </Grid>
                        <Grid xs={12} md={0} lg={0} >
                            <Box  style={{background:'#3B4256',width:'100%',height:'100%',textAlign:'center'}}>
                                <h3>Wykres</h3>
                            </Box>

                        </Grid>
                        <Grid xs={12} md={6} lg={8} css={{height:'75vh'}}>
                            <MyChart campaignId={campaignId}/>
                        </Grid>
                        <Grid xs={3} md={3} lg={2} >
                            <Button color="gradient" onPress={generateCSV} size={'md'} >Generuj CSV</Button>
                        </Grid>

                        <Grid xs={3} md={3} lg={2} css={{justifyContent:'right'}}>
                            <Button color="gradient" size={'md'} onPress={sendWarning} >Poinformuj</Button>
                        </Grid>
                        <Grid lg={4} xs={3} md={3} >
                            <Button size={'md'} color="gradient" onPressEnd={showListOfCampaigns} >Lista Kampanii</Button>
                        </Grid>
                        <Grid lg={4} xs={3} md={3} css={{justifyContent:'right'}}>
                            {/*<Link href="/newCampaign"><Button color="gradient" size={'md'} >Stwórz nową kampanię</Button></Link>*/}
                        </Grid>




                    </Grid.Container>
                {/*</Box>*/}





            </main>
        </>
    )
}