import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import MyNavbar from "@/components/MyNavbar";
import {Grid} from "@nextui-org/react";
import MyTable from "@/components/MyTable";
const inter = Inter({ subsets: ['latin'] })



export default function CampaignDashboard() {
    return (
        <>
            <Head>
                <title>Campaign Dashboard</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MyNavbar title={'Kampania 1'}  />
            <main >
                <div style={{width:'100%',height:'100%'}}>
                    <Grid.Container gap={1} justify="center">
                        <Grid xs={4}>
                            <div className={styles.card} style={{background:'#3B4256',width:'100%',textAlign:'center'}}>
                                <h3>Lista Email</h3>
                            </div>
                        </Grid>
                        <Grid xs={8}>
                            <div className={styles.card} style={{background:'#3B4256',width:'100%',textAlign:'center'}}>
                                <h3>Wykres</h3>
                            </div>

                        </Grid>
                        <Grid xs={4}>
                            <div className={styles.card} style={{background:'#3B4256',width:'100%',height:'70vh'}}>
                                <MyTable/>
                            </div>
                        </Grid>
                        <Grid xs={8}>
                            <div className={styles.card} style={{background:'#3B4256',width:'100%',textAlign:'center'}}>

                            </div>
                        </Grid>

                    </Grid.Container>
                </div>




            </main>
        </>
    )
}