import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import MyNavbar from "@/components/MyNavbar";
import {Grid, Button, Row, Col, Container} from "@nextui-org/react";
import MyTable from "@/components/MyTable";
import {Box} from "@/components/Box";
import MyChart from "@/components/MyChart";
import {useState,useEffect} from "react";



export default function CampaignDashboard() {
    const [csvData, setCsvData] = useState<any[]>([]);

    function back(){
        window.location.href = '/';
    }
    function generateCSV(){
        setCsvData([])

    }
    return (
        <>
            <Head>
                <title>Campaign Dashboard</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main style={{height:'100vh'}}>
                <MyNavbar title={'Kampania 1'}  />
                <Box style={{width:'100%',height:'80%'}}>
                    <Grid.Container gap={1} justify="center" css={{width:'100%',height:'100%'}}>
                        <Grid xs={12} md={6} lg={4} >
                            <Box  style={{background:'#3B4256',width:'100%',height:'100%',textAlign:'center'}}>
                                <h3>Lista Email</h3>
                            </Box>
                        </Grid>
                        <Grid xs={0} md={6} lg={8} >
                            <Box  style={{background:'#3B4256',width:'100%',height:'100%',textAlign:'center'}}>
                                <h3>Wykres</h3>
                            </Box>

                        </Grid>
                        <Grid xs={12} md={6} lg={4} css={{height:'100%'}}>
                            <MyTable campaignId={1} generateCSV={csvData}/>

                        </Grid>
                        <Grid xs={12} md={0} lg={0} >
                            <Box  style={{background:'#3B4256',width:'100%',height:'100%',textAlign:'center'}}>
                                <h3>Wykres</h3>
                            </Box>

                        </Grid>
                        <Grid xs={12} md={6} lg={8} css={{height:'100%'}}>
                            <MyChart campaignId={1}/>
                        </Grid>
                        <Grid xs={3} md={3} lg={2} >
                            <Button color="gradient" onPress={generateCSV} size={'md'} >Generuj CSV</Button>
                        </Grid>

                        <Grid xs={3} md={3} lg={2} css={{justifyContent:'right'}}>
                            <Button color="gradient" size={'md'}  >Poinformuj</Button>
                        </Grid>
                        <Grid lg={4} xs={3} md={3} >
                            <Button size={'md'} color="gradient" >Lista Kampanii</Button>
                        </Grid>
                        <Grid lg={4} xs={3} md={3} css={{justifyContent:'right'}}>
                            <Button color="gradient" onPress={back}  size={'md'} >Powrót</Button>
                        </Grid>




                    </Grid.Container>
                </Box>





            </main>
        </>
    )
}